repos:
- repo: https://github.com/ambv/black
  rev: 18.6b2
  hooks:
  - id: black
    language_version: python3.6
- repo: https://github.com/prettier/prettier
  rev: 9ec1da1ad185a226280212a62a42319965a62ffc
  hooks:
  - id: prettier
    files: '[.]s?css$|[.]ts$|[.]json$'
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v1.3.0  # Use the ref you want to point at
  hooks:
  - id: check-symlinks
  - id: check-merge-conflict
  - id: check-json
  - id: check-byte-order-marker
  - id: check-added-large-files
    args:
    - '--maxkb=1024' # 1 MB is too big
  - id: detect-private-key
  - id: end-of-file-fixer
  - id: flake8
    additional_dependencies:
    - mccabe
  - id: fix-encoding-pragma
  - id: mixed-line-ending
  - id: pretty-format-json
    args:
    - --autofix
  - id: requirements-txt-fixer
  - id: trailing-whitespace
