version: "3"
services:
  backend:
    build: backend
    ports:
    - 9000:9000
    volumes:
    - ./backend:/app
    links:
    - db
  db:
    image: postgres
    restart: always
    ports:
    - 5432:5432
    volumes:
    - db-storage:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: max-torque
      POSTGRES_USER: max-torque
      POSTGRES_DB: max-torque
volumes:
  db-storage: {}
